### ISSUE TITLE
[debops.keyring] Detect if gpg2 is installed

### ISSUE THREAD

**Issue by alinalexandru** [debops/debops#1043]
On Ubuntu below 18, gpg1 is installed.
Gpg1 does not have the --no-autostart option.

**Comment by alinalexandru** [comment]
@drybjed Can this be a solution https://makandracards.com/aslamk/28305-how-to-change-the-default-gnupg-version-from-gpg-to-gpg2 ?

Or you prefer to change the executable when running the command from gpg to gpg2 ?

**Comment by drybjed** [comment]
No, don't mess with either `gpg` or `gpg2` on the host, because lots of other things may expect a specific version.

My solution would be to check the current version of the `gpg` command on the host using the `keyring.fact` script, store that in `keyring__gpg_version` variable, and then change the commands executed in the task depending on the `gpg` version.

**Comment by alinalexandru** [comment]
Is a solution to parse the output from `gpg --version`?
Or do you know other solution for that.

**Comment by drybjed** [comment]
Yes, parsing the output of `gpg --version` would be the way to go. In `gpg` 2.x seems that the first line would suffice.

I plan to tackle various issues listed in [the v1.2.0 milestone](https://github.com/debops/debops/milestone/7) before the next release in late November 2019, so this will be worked on soon.

**Comment by drybjed** [comment]
@alinalexandru Do you know the version of `gpg` which does not have `--no-autostart` which you would want to handle?

Edit: Ah, it was 1.x, so that should be easy. Can you check if the fix works when it gets commited?
