### ISSUE TITLE
[debops.hashicorp] Save HashiCorp local facts failed at second run

### ISSUE THREAD

**Issue by nqb** [debops/debops#1115]
There is an idempotence issue when running  `debops service/hashicorp` several times. First time work as expected but second time failed at `Save HashiCorp local facts` task with following error:
```yml
TASK [debops.hashicorp : Save HashiCorp local facts] **************************************************************************************************************************************************************
fatal: [debops-104949-node1]: FAILED! => changed=false 
  msg: |-
    AnsibleError: Unexpected templating type error occurred on ({% set hashicorp__tpl_application_list = ((ansible_local.hashicorp.applications.keys() if (ansible_local|d() and ansible_local.hashicorp|d() and ansible_local.hashicorp.applications|d()) else []) + hashicorp__applications + hashicorp__dependent_applications) | sort | unique %}
    {% set hashicorp__tpl_applications = {} %}
    {% for entry in hashicorp__tpl_application_list %}
    {%   if (ansible_local|d() and ansible_local.hashicorp|d() and ansible_local.hashicorp.applications|d() and entry in ansible_local.hashicorp.applications.keys()) %}
    {%     set _ = hashicorp__tpl_applications.update({ entry : ansible_local.hashicorp.applications[entry] }) %}
    {%   elif entry in hashicorp__combined_version_map.keys() %}
    {%     set _ = hashicorp__tpl_applications.update({ entry : hashicorp__combined_version_map[entry] }) %}
    {%   endif %}
    {%   if (entry in hashicorp__combined_version_map.keys() and (hashicorp__tpl_applications[entry] != hashicorp__combined_version_map[entry])) %}
    {%     set _ = hashicorp__tpl_applications.update({ entry : hashicorp__combined_version_map[entry] }) %}
    {%   endif %}
    {% endfor %}
    {% set hashicorp__tpl_consul_webui = (ansible_local.hashicorp.consul_webui if (ansible_local|d() and ansible_local.hashicorp|d() and ansible_local.hashicorp.consul_webui|d()) else False) | bool | lower %}
    {% if hashicorp__consul_webui | bool and 'consul' in hashicorp__tpl_applications %}
    {%   set hashicorp__tpl_consul_webui = True %}
    {% endif %}
    {% set hashicorp__tpl_facts = {} %}
    {% set _ = hashicorp__tpl_facts.update({ "applications":      hashicorp__tpl_applications }) %}
    {% set _ = hashicorp__tpl_facts.update({ "bin":               hashicorp__bin }) %}
    {% set _ = hashicorp__tpl_facts.update({ "consul_webui":      hashicorp__tpl_consul_webui | bool | lower }) %}
    {% set _ = hashicorp__tpl_facts.update({ "consul_webui_path": hashicorp__consul_webui_path }) %}
    {% set _ = hashicorp__tpl_facts.update({ "installed":         "true" }) %}
    {{ hashicorp__tpl_facts | to_nice_json }}
    ): unsupported operand type(s) for +: 'dict_keys' and 'list'
```

### Steps to reproduce
1. Create following `hashicorp.yml `file in inventory
```yaml
---
hashicorp__applications: [ 'packer' ]
hashicorp__version_map:
  'packer': '1.4.4'
```
2. Run playbook: `debops service/hashicorp`

### Actual results
Facts on host:
```json
{
    "applications": {
        "packer": "1.4.4"
    },
    "bin": "/usr/local/bin",
    "consul_webui": "false",
    "consul_webui_path": "/srv/www/consul/sites/public",
    "installed": "true"
}
```
Important: on a host which has packer 1.4.3 after updated inventory to bump version to 1.4.4, I noticed following behavior:
- packer has been upgraded to 1.4.4 (as expected)
- current facts are still on old version:
```json
{
    "applications": {
        "packer": "1.4.3"
    },
    "bin": "/usr/local/bin",
    "consul_webui": "false",
    "consul_webui_path": "/srv/www/consul/sites/public",
    "installed": "true"
}
```

### Expected results
Playbook run without errors.

**Comment by drybjed** [comment]
With the rewritten `debops.golang` role I would like to deprecate the `debops.hashicorp` role and instead create roles for each application separately, but that will probably take some time.

Looks like the `debops.hashicorp` fact is just a template file, it should probably be converted to a Python script that checks the available HashiCorp application versions on the remote host and returns them to the Ansible Controller, instead of the Ansible Controller saving the versions itself. This will fix both issues.

**Comment by reixd** [comment]
> [...] I would like to deprecate the `debops.hashicorp` role and instead create roles for each application separately, but that will probably take some time.

Agree, this needs to be done. I tried to use the hashicorp role to install consul and I did not worked quite well.

**Comment by imrejonk** [comment]
This exact AnsibleError caused me to doubt our GitLab runners setup (managed by `debops.gitlab_runner`, of course). All our pipeline runs against DebOps master kept failing when forcing Jane tests with JANE_FORCE_TESTS="true" (or "hashicorp role"). Good to see that I'm not alone in this.

My guess is that this issue will also pop up on the project's CI pipeline on gitlab.com. It doesn't show up there because the hashicorp playbook test is skipped by Jane as there are 'no interesting changes found'. @drybjed, can you maybe run a pipeline with JANE_FORCE_TESTS to confirm this?

Two options I'm thinking about:
1. deprecate the `debops.hashicorp` role and playbook already and remove the test job in .gitlab-ci.yml. This shouldn't be too hard as there are no other playbooks that depend upon this role.
2. fix `debops.hashicorp` just enough to make the test succeed again.

I'm all for option 2. I think it's the cleanest solution which also allows me to use our own DebOps CI pipeline to test our `debops.docker` role (yes, I'm still working on that!). I'll see if I can get a PR ready today.
