### ISSUE TITLE
debops.nginx docs/defaults.rst doesn't exist

### ISSUE THREAD

**Issue by jankowa** [debops/debops#134]
I just wanted to add something to docs and I found that the site
https://github.com/debops/debops/blob/master/docs/ansible/roles/debops.nginx/defaults.rst

doesn't exist. But https://docs.debops.org/en/latest/ansible/roles/debops.nginx/defaults.html does.

```
``nginx_http_access_log``
  Optional, string.
  custom access log configuration in /etc/nginx/nginx.conf
  For example to configure nginx for logging by syslog or change filenames. Overwrites nginx_log_path.


``nginx_http_error_log``
  Optional, string.
  custom error log configuration in /etc/nginx/nginx.conf
  For example to configure nginx for logging by syslog or change filenames. Overwrites nginx_log_path.

```

**Comment by drybjed** [comment]
Ah, sorry about that. The `defaults.rst` pages are generated automatically from `defaults/main.yml` files in the role directories, by `yaml2rst` script. The page you are looking for is [`debops.nginx` default variables file](https://github.com/debops/debops/blob/master/ansible/roles/debops.nginx/defaults/main.yml).

The old documentation had some code that translated the "Edit on GitHub" links to the correct pages; perhaps this could be adapted for the monorepo as well. I'll look into it.

**Comment by jankowa** [comment]
Thansk for info. But where should be the right place to add some info for the 

nginx_http_access_log?

The other nginx_... variables are described in https://docs.debops.org/en/latest/ansible/roles/debops.nginx/defaults.html - but this is autogenerated.

So better to add these variables to defaults/main.yml?

**Comment by drybjed** [comment]
Sure, sounds good to officially expose it via the role defaults. They can still be set in the inventory, however they are only present in the `nginx.conf` template right now.

The `debops.nginx` role is currently poorly maintained. I want to clean it up someday, write proper documentation and put all of the variables in the `nginx__*`namespace. In the past it was very difficult, because the `debops.nginx` role is used as a dependency by many roles in DebOps, and these were in separate repositories at the time. Now, with one `git` repository, it should be much easier to rename the variables and update them elsewhere if necessary.

For the next release (most likely `v0.7.0` I want to streighten up the project repository itself and the code around it like tests, Python scripts, etc. After the release, more extensive role cleanup could take place. At least that are my plans for now.

**Comment by drybjed** [comment]
BTW, if you want to work on the documentation, install Sphinx and the ReadTheDocs theme, at least from `jessie-backports` or on Stretch:
```
apt-get install -yq python-sphinx python-sphinx-rtd-theme graphviz
```
Then you can run the `make docs` command in the DebOps monorepo root directory and browse the generated documentation at `docs/_build/html/index.html`.

**Comment by drybjed** [comment]
The DebOps documentation available at https://docs.debops.org/ should now have correctly rewritten "Edit on GitHub" links for role default variable files, and some others like the project's Changelog. Since this was the main point of this issue, which should be now resolved, I'm closing it.
