### ISSUE TITLE
Provide default for lxc_template_debootstrap_release

### ISSUE THREAD

**Issue by luken** [debops/debops#135]
https://github.com/debops/debops/blob/79236c07027012fbeddc2b003f7f1394e6cec411/ansible/roles/debops.lxc/defaults/main.yml#L212

Another item that is likely due to launching controller from within OSX.

The default behavior if no _release is specifically provided results in an empty ..._release variable and then this error, note the space before the comma.

> Invalid release , valid ones are: squeeze wheezy jessie sid

`lxc_template_debootstrap_release: '{{ ansible_distribution_release | default("stretch") }}'`

I can submit a PR with the above change if you agree.

Next on the list is to figure out why the command below doesn't like stretch as a distro release.  If anyone has any ideas.
`$ lxc-create -n obj01 -t debops -f /etc/lxc/external.conf
debootstrap is /usr/sbin/debootstrap
Invalid release stretch, valid ones are: squeeze wheezy jessie sid
lxc-create: lxccontainer.c: create_run_template: 1297 container creation template for obj01 failed
lxc-create: tools/lxc_create.c: main: 318 Error creating container obj01`

**Comment by luken** [comment]
Updated above, removed the | mandatory as I had hacked up the template file on the LXC host and forgot about the edit, this was likely causing the "stretch" default to be set.

**Comment by drybjed** [comment]
So you are saying that when you run Ansible from macOS, the `ansible_distribution_release` variable is what, empty? That's kinda weird, since Ansible is gathering facts from the remote host, not macOS. What happens if you run:
```
ansible <host> -m setup
```
Do you get "sane" facts, or are variables like `ansible_distriburion`, `ansible_distribution_release`, `ansible_fqdn` missing or empty? What OS release are you using on the remote host you run against?

In the above case I would probably go with the `default()` method, however `ansible_distribution_release` is kinda the default, and its a fact that should be defined by Ansible after facts are gathered. It being missing suggests that something is missing from the remote host that you are running against, and this might impact many more DebOps roles than just `debops.lxc`. I would try and fix this issue first.

**Comment by luken** [comment]
The above Ansible command run from OSX properly comes back with stretch when run against the LXC host:
` "ansible_distribution_release": "stretch",`

other facts seem in order.  I'll keep looking.
