### ISSUE TITLE
Redundant variables in resolvconf.fact

### ISSUE THREAD

**Issue by imrejonk** [debops/debops#1469]
The resolvconf.fact local facts script currently outputs, among other variables, the 'nameserver' and 'search' lists. These lists however are provided through `ansible_dns.nameservers` and `ansible_dns.search` as well. We should consider removing these variables from resolvconf.fact and configure other roles to use the `ansible_dns` variables instead.

**Comment by drybjed** [comment]
Sounds good. We still need a way to track upstream nameservers though. If somebody puts the effort into renaming the references, that's fine with me.

**Comment by imrejonk** [comment]
@drybjed Sure, I can do this. With 'We still need a way to track upstream nameservers' you mean that we should use `ansible_dns` in all roles, right?

**Comment by drybjed** [comment]
No. Some services like `dnsmasq` and `unbound` replace the original nameservers in `/etc/resolv.conf` with themselves, pointing the host to `127.0.0.1` as the "nameserver" and handling the request forwarding. But then Docker comes along and says "Here's an idea: when I make a new container, I'll just get the nameservers from the `/etc/resolv.conf` on the host to point to the same nameservers so that I don't have to generate it randomly". Aaand DNS resolution is broken in containers.

So we fix that in the `docker_server` role and tell Docker to use these specific nameservers instead. But wait, what are the upstream nameservers? Well, thankfully `resolvconf` keeps track of the upstream ones in a separate file that we can read and grab them. And `systemd` has its own, different file with that same data. Now we just need to read these failes and store the nameservers as facts, from where the `docker_server` can get the proper upstream nameservers. Simple.

After all that, keeping the system nameservers, search and domain in the same fact script for completeness is just a formality. And if you want to know why it's even there - I needed the nameserver and search domain information to configure `dnsmasq` and Ansible did not provide `ansible_dns` fact at the time. So again, legacy code. :-)

**Comment by imrejonk** [comment]
@drybjed Ah, I wasn't aware of `ansible_local.resolvconf.upstream_nameservers`. That list will be very useful for `debops.dhcpd` as well :)
So we'll keep that one, but we can remove the 'nameservers', 'search' and 'domain' variables from `ansible_local.resolvconf` once the references are updated, correct?

**Comment by drybjed** [comment]
Sure.
