### ISSUE TITLE
[debops.nullmailer] - falis to start because config files have mode 0600

### ISSUE THREAD

**Issue by jkraemer** [debops/debops#1482]
It seems that the role specifies no mode and the files in `/etc/nullmailer` are created by Ansible with mode 0600 as a default. I helped myself with overriding the `nullmailer__configuration_files` in my inventory and specifying `mode '644'` for all of them, but this should probably be used as a default in the task that processes this list.

- Ansible 2.9.12, Debops 2.1.1, Python 3.7
- Debian Buster on control and managed hosts.

**Comment by nqb** [comment]
Hi,

It's related to Ansible 2.9.12 as reported by @imrejonk on DebOps users mailing list.

See https://github.com/ansible/ansible/issues/71200. This change has been reverted.

**Comment by drybjed** [comment]
Thanks for the bug report. This issue has been fixed in https://github.com/debops/debops/pull/1473/commits/059e685e2f05b81b648d65465f170953327348a7 commit which was backported to the stable branches, but a new stable release hasn't happened yet. I'll to make on during this week.

Also, remember that `/etc/nullmailer/remotes` file needs to be `0600` and owned by `mail:mail`, otherwise you are exposing your SMTP passwords to other local accounts.

**Comment by jkraemer** [comment]
Thanks!

**Comment by imrejonk** [comment]
This was fixed in https://github.com/debops/debops/commit/9496c18e5e11f5009dcc41acb81c4023edf89c0d. You can either update Ansible to 2.9.13, use the `nullmailer` role from master, or wait for a new stable release.
