### ISSUE TITLE
acme-tiny path mismatch on upgrade of debops version

### ISSUE THREAD

**Issue by kosli** [debops/debops#1506]
I was running debops with version 2.1.2 on a previously deployed machine (Debian stretch) and got suddenly the following error:

<pre>TASK [pki : Ensure that acme-tiny is executable]
fatal: [sfers-unifi2]: FAILED! => {"changed": false, "msg": "file (/usr/local/bin/acme-tiny) is absent, cannot continue", "path": "/usr/local/bin/acme-tiny"}</pre>

I can see that the acme-tiny file exists in **/usr/local/lib/pki/acme-tiny** and that it was updated by debops (!).

I assume this is an issue with the recent change to the acme-tiny path & packages (for newer Debian/Ubuntu), but I assume it should not affect the already deployed environments?
Manually copying the file to the new location helped, but I assume that this is not the right way? ;-)

greets
 KoS

**Comment by drybjed** [comment]
Currently the `pki` role installs the `acme-tiny` script when the `git` repository is changed or cloned. Since the change, `acme-tiny` upstream was not updated, so the role did not install the `acme-tiny` script in `/usr/local/bin/` and you got the error. On a new host that won't happen.

I guess a `stat` task that checks if `/usr/local/bin/acme-tiny` is present and if not, installs the script from upstream repository (not when Debian package should be used, of course), could do the trick. I didn't add that kind of check because I try to minimize number of tasks in roles. But perhaps that's a wrong approach to take, the `pki` role is pretty fast already.

**Comment by kosli** [comment]
Thanks @drybjed  
The weird thing is that ```/usr/local/lib/pki/acme-tiny``` got updated...so somehow the file is being pushed there, but afterwards another path is being checked & used?

**Comment by drybjed** [comment]
Hmm, I'm not really sure... I'll try to test this behaviour on a Debian Stretch host to find out what's happening.

**Comment by imrejonk** [comment]
I also encountered this issue today. It only happens on Stretch machines with ACME support enabled in `debops.pki`.
@drybjed, what would you think of replacing the `Install acme-tiny script` task with a task that uses the `file` module to symlink `{{ pki_acme_tiny_bin }}` to `{{ pki_acme_tiny_src }}/acme-tiny/acme_tiny.py` (instead of copying it over)?

**Comment by drybjed** [comment]
@imrejonk Sure, might be a good idea. I'm not sure why I went with the copying instead of symlinking it outright... It was a long time ago. Want to try a PR?

**Comment by imrejonk** [comment]
Will do
