### ISSUE TITLE
Error with debops.journald to create local directory

### ISSUE THREAD

**Issue by gardouille** [debops/debops#1558]
Mainly at the first run of DebOps on a new host, i have an error on *Save Forward Secure Seal verification key on Ansible Controller* task from debops.journald role : 

```
TASK [journald : Save Forward Secure Seal verification key on Ansible Controller] ********************************************************************************************************************************************************************************************************************************************
fatal: [myhost.domain -> localhost]: FAILED! => {"changed": false, "checksum": "0d9a33ba855f7ab9ea196f1bc8c8088dd780e6dc","msg": "Destination directory /home/gardouille/repos/gardouille.debops/ansible/inventory/../secret/journald/fss/myhost.domain does not exist"}
```

At the second run everything works fine… : 
```
ls -l /home/gardouille/repos/gardouille.debops/ansible/inventory/../secret/journald/fss/myhost.domain
.rw------- 43 gardouille 16 Nov 16:42 verify_key
```

Any idea?

**Comment by reixd** [comment]
Hello @gardouille,

looking at the sources of the journald role I found the correspoing failiing task: https://github.com/debops/debops/blob/master/ansible/roles/journald/tasks/main.yml#L79
Apparently the expected directories under `{{ secret + "/" + journald__fss_verify_key_path }}` have not been created yet. Thus failing.

**Comment by Alphix** [comment]
I was bitten by this bug as well on the very first run of DebOps.

The problem is that `journald__fss_enabled` defaults to `False`:
https://github.com/debops/debops/blob/4f600f7e77b4f1acff74cf327311fd3c837bcbab/ansible/roles/journald/defaults/main.yml#L75-L77
https://github.com/debops/debops/blob/4f600f7e77b4f1acff74cf327311fd3c837bcbab/ansible/roles/journald/defaults/main.yml#L58-L62

`journald__fss_enabled` is used early in the `journald` role to determine if the `journald__fss_verify_key_path` secret directory needs to be created:

https://github.com/debops/debops/blob/4f600f7e77b4f1acff74cf327311fd3c837bcbab/ansible/roles/journald/tasks/main.yml#L9-L15

Later, `journald` local facts are stored:
https://github.com/debops/debops/blob/4f600f7e77b4f1acff74cf327311fd3c837bcbab/ansible/roles/journald/tasks/main.yml#L23-L28

And updated:
https://github.com/debops/debops/blob/4f600f7e77b4f1acff74cf327311fd3c837bcbab/ansible/roles/journald/tasks/main.yml#L30-L32

But in the updated local facts, `persistent` is true if `/var/log/journal` exists:
https://github.com/debops/debops/blob/4f600f7e77b4f1acff74cf327311fd3c837bcbab/ansible/roles/journald/templates/etc/ansible/facts.d/journald.fact.j2#L29-L31

Which it does on a vanilla Debian stable installation as far as I can tell:

```
$ cdebootstrap --include=systemd-container,iproute2,procps,python3,openssh-server --flavour=minimal stable /var/lib/machines/test
...
$ machinectl start test
$ machinectl shell test
Connected to machine test. Press ^] three times within 1s to exit session.
root@test:~# ls -al /var/log/journal/
total 12
drwxr-sr-x+ 3 root systemd-journal 4096 Jan 23 11:08 .
drwxr-xr-x  5 root root            4096 Jan 23 11:08 ..
drwxr-sr-x+ 2 root systemd-journal 4096 Jan 23 11:08 0025efb0d74fb0e7b750945f600bf48d
```

So, after the local facts are updated, `ansible_local.journald.persistent` and `journald__fss_enabled` change to `True` and `FSS` keys are created even though the secret directory has not been created.

Not sure what the best fix is, but for now you could set `journald__fss_enabled` to `True` in your inventory.

@drybjed - ?

**Comment by drybjed** [comment]
@alphix: nice work with determining the exact reason this happens. That certainly throws a wrench in the works, but I think that I see a solution. We can just move the `import_role` task to after the Ansible local facts are updated, then it should work as expected. Could you try that and see if it fixes the issue?

**Comment by Alphix** [comment]
@drybjed Yep, works for me with this change:

```
$ git diff | cat
diff --git a/ansible/roles/journald/tasks/main.yml b/ansible/roles/journald/tasks/main.yml
index 4623ea282..96bee83bf 100644
--- a/ansible/roles/journald/tasks/main.yml
+++ b/ansible/roles/journald/tasks/main.yml
@@ -6,14 +6,6 @@
 - import_role:
     name: 'ansible_plugins'
 
-- import_role:
-    name: 'secret'
-  vars:
-    secret__directories:
-      - '{{ (journald__fss_verify_key_path | dirname)
-            if journald__fss_enabled|bool
-            else [] }}'
-
 - name: Make sure that Ansible local facts directory exists
   file:
     path: '/etc/ansible/facts.d'
@@ -31,6 +23,14 @@
   action: setup
   when: journald__register_facts is changed
 
+- import_role:
+    name: 'secret'
+  vars:
+    secret__directories:
+      - '{{ (journald__fss_verify_key_path | dirname)
+            if journald__fss_enabled|bool
+            else [] }}'
+
 - name: Move persistent journal to volatile storage if requested
   command: 'journalctl --relinquish-var'
   when: (journald__enabled|bool and journald__version is version("244", ">=") and
```

**Comment by drybjed** [comment]
Thanks for checking, I'll make a fix ASAP.

**Comment by Alphix** [comment]
@drybjed : out of curiosity, why is the handling of the `secret` dir so different in `journald` when compared to e.g. `tinc`? (which does it via `main_env.yml`, etc)....

**Comment by drybjed** [comment]
The handling in the `tinc` role was done long ago, use via `import_role` is a recent change and not all roles are updated for the new way to do things. So - inertia, I guess? :-)

**Comment by gardouille** [comment]
Woohoo, perfect, many thanks !
