### ISSUE TITLE
wpcli role - why does it install version which is two years old?

### ISSUE THREAD

**Issue by ser** [debops/debops#1820]
wpcli role has hardcoded version into defaults - why? 

The docs on main site read how to get current version:

```
curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
```

Why the author decided to hardcode the version instead of getting a current one?

**Comment by drybjed** [comment]
Hi, author of the `wpcli` role here. The role was created two years ago when version `v2.2.0` was the newest one. Because we are downloading files directly from the webserver, I wanted to make sure that we are getting correct ones, checked via a checksum stored in the role. Also, since the expectation is that this role is used in a production environment, I wanted to avoid updating the version of the installed script without verification that it works first.

Since it was a while, I think we can bump the version if you want.

**Comment by imrejonk** [comment]
It would be so nice to see wp-cli packaged in Debian. There have been some attempts, but these didn’t lead to fruition due to lack of effort: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=692353

**Comment by alinalexandru** [comment]
My PR can be accepted until it will added in Debian :D
