### ISSUE TITLE
Possible security hole in debops.authorized_keys role?

### ISSUE THREAD

**Issue by jrgoldfinemiddleton** [debops/debops#184]
I might be missing something but I am concerned that the authorized_key task "fails over" to the root user for the "user" parameter if the specified user isn't found in the passwd DB.  Wouldn't this logic allow an erroneous key to give full root access?

https://github.com/debops/debops/blob/a34cdcaab6ca9e5154ab64116a75ed03c1cbd331/ansible/roles/debops.authorized_keys/tasks/main.yml#L48

My apologies if I'm being dense.

**Comment by drybjed** [comment]
I don't think that this is a security hole. Please note that the `item.name` parameter is required by the task, otherwise it's skipped. The path of the file that the `authorized_key` module will include the SSH key in will be in effect:
```yaml
/etc/ssh/authorized_keys/{{ item.name }}
```
The `user` parameter of the `authorized_key` Ansible module is a required parameter, without it the module fails. However, the user specified in the configuration might not exist at the time the `debops.authorized_keys` role is executed. Since the `omit` value, which would cause the `user` parameter to not be processed by Ansible, cannot be used, the next best thing is to use an user account which will definitely be present - `root`.

The result is a file named after the specified UNIX user account, owner by `root:{{ item.name }}`, with `0600` permissions. Consider that the `sshd` daemon uses the username to lookup the correct file in the `/etc/ssh/authorized_keys/` subdirectory, and that the lookup is done with the privileges of that user account, not `root` - even if the file matches the username, the service will not have access to it due to `0600` permissions (that's why the role handles this with an additional task that changes the permissions to the `0640` so that an user account can read it). And if the account has access, the SSH keys will give access to that specific account, not `root`.

Edit: sorry, I forgot that the role created the UNIX group based on `item.name` parameter. Fixed the above group ownership.

**Comment by jrgoldfinemiddleton** [comment]
Oh, I see.  So there is no way that someone trying to SSH using root will be able to get opensshd to consider the keys in any file other than "root" inside the "/etc/ssh/authorized_keys" directory (aside from perhaps "/root/.ssh/authorized_keys")?

By the way, thank you for the detailed and quick reply.

I am interesting in submitting PRs for the other issues I've reported.  I will try to get to it today.

**Comment by drybjed** [comment]
For that you would need to review the `sshd` source code, but as far as I can tell, no. One option to do that would be to change the `AuthorizedKeysFile` option in the `/etc/ssh/sshd_config` file to point to a static file, say `/etc/ssh/authorized_keys/root` as one of the files checked by the daemon. Or, use the `AuthorizedKeysCommand` to execute a script that returns the SSH keys from the specified file.

Looking forward to the PRs. :-)

**Comment by jrgoldfinemiddleton** [comment]
Thank you.  I really appreciate this great project.
