### ISSUE TITLE
use iptables legacy be default

### ISSUE THREAD

**Issue by 532910** [debops/debops#1888]
ferm doesn't work well with iptables/ebtables-nft and starting with bullseye it uses legacy tools directly, regardless of the alternatives setting: https://github.com/MaxKellermann/ferm/issues/47

nft tools are used by default which is confusing as they show "empty" rules

I believe ferm role should change alternatives for iptables and ebtables to legacy versions.

**Comment by 532910** [comment]
https://docs.debops.org/en/master/ansible/roles/ferm/defaults/main.html#envvar-ferm__iptables_backend_path

in fact it has nothing common with ferm on bullseye

**Comment by imrejonk** [comment]
Sounds like a good idea, I was confused by the empty nftables rules on Bullseye as well. Let's revert to the legacy iptables until ferm has proper nftables support.

**Comment by 532910** [comment]
> until ferm has proper nftables support

It's not going to happen: https://github.com/MaxKellermann/ferm/issues/35

**Comment by dnyfrs** [comment]
Hello. This situation breaks my setup with docker and libvirtd installed in Debian Bullseye.
When i run libvirtd and related roles i can see the iptables rules, however, when i run the docker_server role on top of it; that's when all the rules are getting messed up and VMs in libvirtd breaks connection to the outside world.
Do you have any suggestions?

Thanks in advance.

**Comment by imrejonk** [comment]
This was fixed in #1942. We reverted to legacy iptables in the `debops.ferm` role. Unfortunately the ferm developers have decided to not support nftables, meaning that we are stuck with the current situation until a role is developed for managing nftables. You are suggested to remove the nftables configuration from your system for now.

A few DebOps developers, including myself, are looking at [firewalld](https://firewalld.org/) as an alternative to ferm. firewalld supports nftables and has its own [module](https://docs.ansible.com/ansible/latest/collections/ansible/posix/firewalld_module.html) in the `ansible.posix` collection.
