### ISSUE TITLE
docker debops: error: the following arguments are required: section

### ISSUE THREAD

**Issue by niccolox** [debops/debops#1949]
is this is a new feature or have I missed something? 

Using the latest docker images on Mac Os

```
❯ docker run -it --rm debops/debops
Unable to find image 'debops/debops:latest' locally
latest: Pulling from debops/debops
7d63c13d9b9b: Pull complete
f7a99f68f7fa: Pull complete
4a24c884eda7: Pull complete
ff23b1e8108b: Pull complete
b8676df2b5a4: Pull complete
815afffc10ad: Pull complete
Digest: sha256:bc600c9a637163e93b45f904a7407c11621c16a8fd0bbd940d7bd330db0054fe
Status: Downloaded newer image for debops/debops:latest
Created new DebOps project in /home/ansible/src/controller
ansible@b607c029dee3:~$ cd ~/src/controller
ansible@b607c029dee3:~/src/controller$ debops
usage: debops <section> [<args>]

Sections:
    project  manage project directories
    run      run Ansible playbook(s) against hosts
    check    run Ansible playbook(s) in check mode
    config   display DebOps configuration options
debops: error: the following arguments are required: section
ansible@b607c029dee3:~/src/controller$
```

**Comment by drybjed** [comment]
A [new set of DebOps scripts](https://lists.debops.org/hyperkitty/list/debops-users@lists.debops.org/thread/QRAEUWALRQ5SWVZXNM52YWD7HJXUYUVV/) has been created in the `master` branch. The `debops` command now has a set of subcommands you need to use, check its manual pages (`man debops`, `man debops-run`, etc.). The equivalent of the

```bash
debops
```
command in the new scripts is:
```bash
debops run site
```
The scripts are still in development and have some issues - that's why there was no release yet. I plan to make a PyPI release in January 2022.

**Comment by niccolox** [comment]
OK, thanks, can I pin to a docker image that is "stable"?

**Comment by niccolox** [comment]
closing this, went the different direction
