### ISSUE TITLE
ansible-lint breaking change: either implement fqcn-builtins or disable it explicitly in config

### ISSUE THREAD

**Issue by ssbarnea** [debops/debops#2027]
v6 of ansible-lint will report like >5000 errors on this repository due to `fqcn-builtins` becoming enabled by default.

I found this while working on https://github.com/ansible-community/ansible-lint/pull/1908/files

**Comment by drybjed** [comment]
Thanks for the heads up. Can you tell me more about `fqcn-builtins`? I'll check `ansible-lint` repository in the meantime...

**Comment by drybjed** [comment]
Ah, according to [this rule](https://github.com/ansible-community/ansible-lint/blob/98007d5107e3f1bc720700b002d89f41955ebe3d/src/ansiblelint/rules/FQCNBuiltinsRule.py) `ansible.builtin.*` stuff should be called explicitly, I guess due to Ansible dropping the redirects at some point. Can we deal this by adding `ansible.builtin` to the playbook or role `collections:` list?

Otherwise a proper way to deal this would be to update those 5000 entries, since DebOps is supposed to be a reference for `ansible-lint` now. Just ignoring a rule like this globally defeats that purpose. The `v3.0.x` version was just released, so it's a perfect time to do a massive change like that.

**Comment by ssbarnea** [comment]
We plan to add auto-fixing but I bet it will not land into the first release of v6.

I think that one temporary measure would be to add
```
# .ansible-lint
skip_list:
- fqcn-builtins  # temporary until we fix them
```

Hint: there are few gotchas, like `synchronize` becomes `ansible.posix.synchronize`.

I am afraid that using collections would not save you from using fully qualified names.

If you want to work on it you can enable the list even now, just add it to `enable_list`. The rule is not new, but it was one of very few opt-ins.

**Comment by drybjed** [comment]
Oh, that's an excellent tip, thanks. Any other opt-ins worth checking out?

**Comment by ssbarnea** [comment]
Take a look at https://github.com/ansible-community/ansible-lint/blob/main/.ansible-lint#L43-L49 -- i had the habbit of keeping all the optins in the sample config.

**Comment by drybjed** [comment]
@ssbarnea The `master` DebOps branch has been updated, `ansible.builtin` modules should now be referred by their FQCNs. Can you check if `ansible-lint` tests for the DebOps repository work as expected?
