### ISSUE TITLE
nullmailer update asks questions on `apt upgrade` when installed via debops

### ISSUE THREAD

**Issue by jankatins** [debops/debops#237]
I installed nullmailer via running `debops`. Afterwards I did a `apt update && apt upgrade` and got asked by the nullmailer package how to configure nullmailer. This seems wrong: if I configure it via debops, I want to have the package in a state that it doesn't ask me questions on updates afterwards.

**Comment by drybjed** [comment]
Agreed. Do you know what questions were you asked by `debconf`? Also, what OS, release?

**Comment by jankatins** [comment]
debian with latest unstable. There were two questions: the second was about the smarthost setting, the first i don't remember anymore. 

the upgrade of nullmailer (from etckeeper log):

```
    -nullmailer 1:2.1-5 amd64
    +nullmailer 1:2.1-7 amd64
```

**Comment by drybjed** [comment]
Could you install `debconf-utils` and run:
```
debconf-get-selections | grep nullmailer
```
This list could be compared with the one in Debian Stable, that should show the missing questions.

**Comment by jankatins** [comment]
```
λ debconf-get-selections | grep nullmailer
nullmailer	shared/mailname	string	littlebottom2.local.katzien.de
nullmailer	nullmailer/defaultdomain	string	local.katzien.de
nullmailer	nullmailer/adminaddr	string	root@local.katzien.de
nullmailer	nullmailer/relayhost	string	
```

**Comment by drybjed** [comment]
Hmm... So, on my systems `debconf` doesn't ask about `nullmailer` questions on upgrade, but that might be different on Debian Sid. Currently the role doesn't set any `debconf` questions, but perhaps that could be changed. I didn't want to go the `debconf` route because at the time the [remote server password was left in the `debconf` database in the clear](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831813), but that seems to have been fixed. In any case, I'll move this issue to the `v0.8.0` release for now.

**Comment by drybjed** [comment]
@jankatins I've looked at this issue again, and I'm not sure if it can be currently fixed on the Ansible role level. The `nullmailer/relayhost` debconf question is cleared after the `nullmailer` package is installed [because it introduced a security bug by leaking smarthost credentials via the debconf database](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831813). The issue is, I think, on the Debian package side - debconf sees the `nullmailer/relayhost` parameter as empty so it asks the user for the value. The `debops.nullmailer` role could fill that parameter in, but that just reintroduces the credential leak.

I would ask the `nullmailer` Debian package maintainer about a possible solution for this, especially that you reported this issue on Debian Sid. The fix could be included in Debian Buster that way.
