### ISSUE TITLE
bookworm: security repo not found

### ISSUE THREAD

**Issue by htgoebel** [debops/debops#2385]
On a fresh installed bookworm machine (after running playbook `site`):
```
root@app1:~# apt-get update 
Get:1 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Ign:2 https://security.debian.org/debian-security bookworm InRelease               
Hit:3 https://deb.debian.org/debian bookworm InRelease                             
Get:4 https://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]           
Ign:5 https://security.debian.org/debian-security bookworm-updates InRelease       
Ign:6 https://security.debian.org/debian-security bookworm-backports InRelease     
Hit:7 http://debian.mirror.lrz.de/debian bookworm InRelease                     
Get:8 https://deb.debian.org/debian bookworm-backports InRelease [49.7 kB]
Err:9 https://security.debian.org/debian-security bookworm Release         
  404  Not Found [IP: 151.101.194.132 443]
Get:10 http://debian.mirror.lrz.de/debian bookworm-updates InRelease [52.1 kB]  
Get:11 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [47.3 kB]
Get:12 http://debian.mirror.lrz.de/debian bookworm-backports InRelease [49.7 kB]   
Err:13 https://security.debian.org/debian-security bookworm-updates Release
  404  Not Found [IP: 151.101.194.132 443]
Err:14 https://security.debian.org/debian-security bookworm-backports Release
  404  Not Found [IP: 151.101.194.132 443]
Reading package lists... Done
```

**Comment by prahal** [comment]
Maybe you want to retitle this issue.
The security repo is found:
`Get:1 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]`

To me, the issue is that other repositories are also appended -security while they should not and these are the broken ones (vanilla repo, updates, and backports ones):
```
Err:9 https://security.debian.org/debian-security bookworm Release         
  404  Not Found [IP: 151.101.194.132 443]
Err:13 https://security.debian.org/debian-security bookworm-updates Release
  404  Not Found [IP: 151.101.194.132 443]
Err:14 https://security.debian.org/debian-security bookworm-backports Release
  404  Not Found [IP: 151.101.194.132 443]
```

There are also correct repository URLs for these:
```
Hit:3 https://deb.debian.org/debian bookworm InRelease                             
Get:4 https://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]    
Get:8 https://deb.debian.org/debian bookworm-backports InRelease [49.7 kB]       
Get:10 http://debian.mirror.lrz.de/debian bookworm-updates InRelease [52.1 kB]  
```

The bug might well be in the debops apt role that appends "-security" to the URL.
I do not know when I will have time to investigate why (it might only affect installs from scratch).
https://github.com/debops/debops/blob/master/ansible/roles/apt/defaults/main.yml#L585

But are you confident this install is vanilla? because I see `debian.mirror.lrz.de` in the URLs (could be debian installer adding this one though).

Can you share the bogus /etc/apt/sources.list and /etc/apt/sources.list.d files?

**Comment by htgoebel** [comment]
I tested this with a totally vanilla installation, and the repos are misconfigured, too. 
So given @prahal's analysis, I assume this issue is a duplicate of #2380. I'll add more information there.

**Comment by prahal** [comment]
@htgoebel could you close this issue?
(ie I do not have the right to close it and it seems there is no point in having the dev close it for us).
Seems you moved the discussion to #2380 as this issue is likely a duplicate.
