### ISSUE TITLE
debops.cryptsetup uses `dd` option that is unsupported on macos

### ISSUE THREAD

**Issue by jinnko** [debops/debops#31]
I'm using debops.cryptsetup from a macos controller and have found that the [command to generate the encryption key](https://github.com/debops/ansible-cryptsetup/blob/master/tasks/manage_devices.yml#L37) on the ansible controller makes use of the `dd` option `iflag=fullblock`.  This option isn't available to the default macos version of `dd`.

I can think of three ways to address this:

1. Remove the `iflag=fullblock` option.  From the man page this option will `accumulate full blocks of input`.  It seems to me this is a "nice to have" option rather than a requirement, but I'm not certain.
2. Use something other than `dd`.  I'm thinking `openssl` might be a suitable alternative.
3. Determine whether the controller is `darwin` or `linux` in a prior task, then conditionally include or exclude the option.

It seems to me option 1 may acceptable, though I'm happy to explore the other options too and raise a PR.

**Comment by drybjed** [comment]
The `debops.pki` role [checks various things on Ansible Controller](https://github.com/debops/debops/blob/master/ansible/roles/debops.pki/tasks/main.yml#L41-L74), you could do something similar if it's needed.

Calling @ypid in case he hasn't seen the issue yet.

**Comment by ypid** [comment]
> Remove the iflag=fullblock option. From the man page this option will accumulate full blocks of input. It seems to me this is a "nice to have" option rather than a requirement, but I'm not certain.

We can not do this. "accumulate full blocks of input" is of crucial importance here as explained in [Create random data with dd and get “partial read warning”. Is the data after the warning now really random?](https://unix.stackexchange.com/questions/121865/create-random-data-with-dd-and-get-partial-read-warning-is-the-data-after-the). Without the `iflag=fullblock` and because of the blocking nature of `/dev/random` it would be very likely that `dd` only reads partial blocks which will result in a much smaller key size than what we specified. In the worst case, dd would only return one byte of maybe even none at all which would then be used as your key. I guess I don’t need to tell you how easy that would be to brute force. We can not allow this to happen.

> Use something other than dd. I'm thinking openssl might be a suitable alternative.

> openssl rand - generate pseudo-random bytes

That is not what I would like to use when I am on GNU/Linux. I want the real thing.

> Determine whether the controller is darwin or linux in a prior task, then conditionally include or exclude the option.

You mean `iflag=fullblock`? Well, I don’t use Apple stuff but I would not do this to my worst enemy :)

I would propose a different fix. 

```YAML
cryptsetup__keyfile_gen_type: '{{ "text" if (ansible_os_family == "darwin") else "binary" }}'
```

Not sure if `pwgen` is available on OSX. You might need to change `cryptsetup__keyfile_gen_command` in a similar way if there is something more convinient which is rated for outputting cryptographically secure passphrases.

Please add a note to the docs. Also, note https://github.com/debops/debops-playbooks/issues/400. Thanks very much and we are looking forward to a PR.

**Comment by ypid** [comment]
> I believe ansible_os_family will return the OS of the target host rather than the local controller OS.

You are right. I missed that. I also don’t know of a way to do this. One workaround might be to check for a file which always exists on one of the platforms but never (or at least almost never which would be good enough) on the other.

```YAML
- debug:
    msg: '{{ "File exists, I am on GNU/Linux" if lookup("fileglob", "/etc/environment") else "Not on GNU/Linux" }}'
```

I just made up the `/etc/environment`. A suitable file would need to be found.

**Comment by ypid** [comment]
@jinnko Any updates?

**Comment by jinnko** [comment]
@ypid not yet - planning to have a look at this again in the next couple of weeks.

**Comment by stek29** [comment]
What's wrong with just using `head -c <if >of` as suggested in stackexchange answer?

**Comment by ypid** [comment]
@stek29 Thanks for the input. That should work, https://github.com/debops/debops/pull/232. Please review.

**Comment by stek29** [comment]
@ypid `head -c`, not `head --byte` :(
