### ISSUE TITLE
cron of Diffie-Hellman ephemeral parameters kills LXD container host

### ISSUE THREAD

**Issue by ser** [debops/debops#359]
we currently generate DH ephemeral parameters monthly via ```/etc/cron.d/dhparam-generate-params```:

```
@monthly root test -x /usr/local/lib/dhparam-generate-params && /usr/local/lib/dhparam-generate-params schedule
```

The problem arrives when it's done on a LXD containers host server with dozens of machines, it simply might kill the server as all generations start in the same time. 

How can we make timing more random by default?

**Comment by drybjed** [comment]
That would probably happen the same with VM/container hosts with multiple machines... As far as I'm aware, the common method to deal with this is to add a random `sleep` delay to a script, for example the `apt` cron script did that [at least up until Jessie](https://sources.debian.org/src/apt/1.0.9.8.4/debian/apt.cron.daily/#L281-L297). I'm not sure how that behaves with `cron` though - does it wait for the `apt` script to finish before running the next one in `/etc/cron.daily/` directory? I think that would be the case due to `run-parts` running scripts one by one.

In Stretch onwards, the `apt` cron script was replaced by a [systemd timer](https://sources.debian.org/src/apt/1.4.8/debian/apt-daily.timer/#L6) and `apt-daily.service` which supports random delays. Perhaps that's the correct way forward - setup a timer service on Jessie, Stretch, etc., and leave the `cron` script optional for cases like Devuan which don't use `systemd`.

**Comment by ser** [comment]
OK I will propose something for systemd based distros, then. Thanks.
