### ISSUE TITLE
is it wise for unattended upgrades to be enabled for non-security packages by default in debops common playbook?

### ISSUE THREAD

**Issue by fermulator** [debops/debops#387]
Hi there,

First time user of debops in my environment. Getting a feel for things.

Before blindly running debops common on my hosts, I wanted to fully understand what defaults are fired in.

This issue raised is the default consideration of the default settings for unattended upgrades as per:
- https://github.com/debops/debops-playbooks/blob/master/playbooks/common.yml#L130
- https://github.com/debops/debops/blob/master/ansible/roles/debops.unattended_upgrades/defaults/main.yml

Should we _really_ be enabling unattended upgrades for ALL packages on systems by default? System administrators _MUST_ certainly enable security packages by default (which is common practice and I've already done of course on my systems, before debops as per https://help.ubuntu.com/community/AutomaticSecurityUpdates).  However auto-updating other packages can be considered risky for production systems as it may incur random breakages to the applications running on those systems.

It is (to my knowledge) best practice for Linux system administrators to schedule package updates and verify application compatibility on some sane schedule according to their company/personal policy/preference balancing risk vs. effort.

---
raising this for open opinion/discussion

Thank you!

**Comment by drybjed** [comment]
Just for the record, configuration of `unatteneded-upgrades` [depends on presence of a domain in `ansible_domain` variable](https://github.com/debops/debops/blob/master/ansible/roles/debops.unattended_upgrades/defaults/main.yml#L22-L33). The idea behind this decision is that DebOps can be used both on a standalone host (say, a workstation or a laptop) without a specific domain set, or in a cluster environment where there should be a domain set. Policies for these environment differ in my personal opinion - on a workstation you might want to upgrade all packages automatically since you work with it all the time, it's local host with easy console access. In a cluster environment it becomes tricky if an upgrade breaks only means of remote access to a host in case some fix is needed, therefore a more restrained approach is taken.

Of course it all depends on use of Debian Stable as the base OS release in both cases. If you tend to use Debian Testing or even Debian Unstable on a workstation this approach is definitely invalid. Perhaps `debops.unatteneded_upgrades` role could check if current Stable release is used and enable/disable upgrades for all packages based on that, in addition to a presence of a domain.

What do you think about this reasoning, is it sound or would you want to see a different approach?

**Comment by fermulator** [comment]
Thoughts:
- the conditional on domain or not feels irrelevant to me (presumably it was added for a reason - but I'm left wondering if this bifurcated assumption is true for all users)
- at minimum your proposal to check "if base-stream=stable" is an improvement
- regardless, my change proposal might not be desirable depending on the user-community-base (do "most people prefer" and rely on the current defaults?)

My _personal_ strategy (for both stable workstation and production servers) is to err on the side of caution -- by default only enable security updates. I _hate_ being surprised by breakage and having to guess what broke and why. At least when it's manual/periodic in the user's control, A) they can see the packages being updated and make quick risk assessments, and B) immediately following updates breakages are more quickly tracked down.

Organizations with a full-time sysadmin staff can probably handle these in their rare occurrences, but for personal or part-time (small org) situations, typically production servers have pkg updates disabled to prefer stability.

For DebOps, this is my preference too (do not auto-update all), but of course if the user desires it, they should run a specific (non-common) playbook to enable ALL package updates.

Regardless, the result+assumptions we decide should be documented completely: https://docs.debops.org/en/latest/debops-playbooks/guides/getting-started.html#configure-the-remote-host

**Comment by drybjed** [comment]
As far as I can tell, a common practice in larger production environments is to set up a local package repository mirror from which all of the production hosts pull packages. That way you have a controlled ingress point for new updates and can release them after checking that everything works as expected in a staging environment, and the hosts just pull new updates via `unattended-upgrades` as they show up in the local mirror. But that's on a whole different level.

I haven't seen anybody complain yet about the defaults used in `debops.unattended_upgrades`, specifically the auto upgrade of all packages when not in a domain environment. But if you feel that changing the default to not be clever about enabling upgrades for all packages and let the sysadmin decide the preferred policy is a better way, I'm fine with that. And this should be mentioned in the getting started docs as well, so that admins are aware what the defaults are and where they can be changed. Want to make a PR that changes the setting and adds a few documentation paragraphs about it?
