### ISSUE TITLE
[debops.python] Problem installing python packages with bootstrap playbook on bionic

### ISSUE THREAD

**Issue by carlalexander** [debops/debops#407]
I'm in the process of testing my debops setup for the new Ubuntu LTS. I'm running into a problem with the `bootstrap` playbook trying to install the packages. Specifically, it seems that `apt -q update` isn't running as defined [here](https://github.com/debops/debops/blob/master/ansible/roles/debops.python/raw/tasks/main.yml#L5-L7). Because of that, it can't find all the python packages that it needs to install.

Is there a reason `apt -q update` isn't just running all the time?

**Comment by drybjed** [comment]
The `apt-get update` command won't be executed if the package information has been updated during last 12 hours. Did you install that Ubuntu host yourself via an installer, or was that host cloned from an image, say by a VPS provider?

I suppose that this could be changed to be conditional so that users can enable/disable the update as needed or change the timeframe. I'll see what I can do.

**Comment by drybjed** [comment]
The https://github.com/debops/debops/pull/408 patch should help in this case. @carlalexander, can you check if this solves the issue by setting the variable to `0` in your case?

**Comment by carlalexander** [comment]
I'm using the Digital Ocean image. The #408 patch did the trick! I have no idea why it doesn't have all the python packages even if the cache is less than 12 hours old. I guess I'll force it to `0` for now.
