### ISSUE TITLE
ferm install results in upnp clients not finding anything (e.g. vlc not finding DLNA Servers)

### ISSUE THREAD

**Issue by jankatins** [debops/debops#452]
I used debops to install (up to now partially) my local laptop. It installed the ferm firewall. The installed ferm rules apparently disabled UPNP finding my DLNA server (twonky on my Qnap NAS) in VLC and others. After purging `ferm` the DLNA server is shown again in `vlc` (and `gupnp-universal-cp` from `gupnp-tools` package).

I'm not sure what to make of this. For now I will just keep ferm purged. A special rule to let upnp traffic (for a local client!) through would be nice (I've no clue what ferm rule that would be :-( ). 

And just to make the next googler happy, this is the output you will see in when starting vlc on the commandline with debugging enabled (`vlc -vvv`) and clicking `View -> Playlists -> Local Network -> Universal Plug 'n Play`:

```
[...]
main services discovery debug: looking for services_discovery module matching "upnp": 15 candidates
upnp services discovery: Initializing libupnp on 'default' interface
main services discovery debug: using services_discovery module "upnp"
upnp services discovery warning: search timeout
upnp services discovery warning: search timeout
```

**Comment by drybjed** [comment]
You can set in the Ansible inventory of this host:
```
ferm__enabled: False
```
This will ensure that `debops.ferm` role will be handled correctly in various DebOps roles. `ferm` will be installed, but will not manage the firewall.

After looking for a bit, it seems that [uPNP requires some advanced firewall tricks to work](https://forum.syncthing.net/t/upnp-and-iptables/2644/7). I guess for starters you could just allow everything from your own network to connect to any port, that should do the trick:
```
ferm__host_rules:
  - name: 'allow-all'
    type: 'accept'
    saddr: [ '192.0.2.0/24' ]
```
Something more advanced could be added later into DebOps. I'm currently not using uPNP myself, so that might take a while.
