### ISSUE TITLE
debops.nginx seems to require sudo

### ISSUE THREAD

**Issue by myrdd** [debops/debops#516]
I'm using the debops roles without DebOps, as described in the ”example playbook“ documentation sections.

I've been executing `debops.gitlab`, and ansible failed at this `debops.nginx` task:

https://github.com/debops/debops/blob/2806b5517dfa69ba8eb08ea1c49b5726c75209ca/ansible/roles/debops.nginx/tasks/main.yml#L126-L133

because `Destination directory /etc/sudoers.d does not exist`.

Sudo is not installed on my systems by default. Should `sudo` be added to

https://github.com/debops/debops/blob/2806b5517dfa69ba8eb08ea1c49b5726c75209ca/ansible/roles/debops.nginx/defaults/main.yml#L53

or should the task (_”Allow webadmins to control nginx system service using sudo“_) be skipped if `sudo` is not installed?

Possibly related: https://github.com/debops/debops/issues/165

**Comment by drybjed** [comment]
Thanks for the bug report. :-) This is a tricky issue with different solutions.

Adding `sudo` to list of installed APT packages kind of defeats the purpose if you don't want `sudo` on your systems, or if you use `sudo-ldap` which would be then uninstalled - that's why `debops.sudo` role exists to centralize this in the future.

Adding `debops.sudo` role as a dependency to `debops.nginx` would require including it in all of the various roles that use `debops.nginx`, and since `sudo` is not as essential as `ferm` for example to Nginx operation, I wouldn't do it.

But, there's now another option - we can easily execute that task conditionally based on the existence and value of `ansible_local.sudo.installed` boolean variable. Of course you need to check all of the `ansible_local` dictionaries in the "path" to make sure it works on hosts without `debops.sudo` role applied.

Want to try and make a PR? If not, I can do it in a day or two.

**Comment by myrdd** [comment]
I'm testing the `ansible_local.sudo.installed` for the nginx (+gitlab) case right now and I will create a PR. :)
