### ISSUE TITLE
Vagrant: usage of REAL_HOSTNAME variable

### ISSUE THREAD

**Issue by nqb** [debops/debops#545]
Hello,

If you use this configuration:
```
export VAGRANT_HOSTNAME=foo
export VAGRANT_NODES=1
vagrant up
vagrant up node1
```

The two VM will not work due to `systemd`.

master debug:
```
    master: ++ REAL_HOSTNAME=
    master: ++ '[' -n foo ']'
    master: ++ export REAL_HOSTNAME=foo
    master: ++ REAL_HOSTNAME=foo
    master: ++ '[' -n foo ']'
    master: +++ dnsdomainname -A
    master: ++ current_fqdn=
    master: ++ jane notify info 'Changing box hostname to '\''foo'\''...'
    master: JANE:V:INFO: Changing box hostname to 'foo'...
    master: ++ '[' -d /run/systemd/system ']'
    master: ++ hostnamectl set-hostname foo
    master: +++ systemctl is-active systemd-networkd.service
    master: ++ '[' inactive == active ']'
    master: ++ jane notify info 'Requesting restart of '\''networking.service'\''...'
    master: JANE:V:INFO: Requesting restart of 'networking.service'...
    master: ++ systemctl restart networking.service

```

node1 debug:
```
    node1: ++ REAL_HOSTNAME=ci-702e7442-d7b0-4726-9fbf-5fb896b3c99e
    node1: ++ '[' -n ci-702e7442-d7b0-4726-9fbf-5fb896b3c99e ']'
    node1: ++ jane notify info 'Changing box hostname to '\''ci-702e7442-d7b0-4726-9fbf-5fb896b3c99e'\''...'
    node1: JANE: notify info Changing box hostname to 'ci-702e7442-d7b0-4726-9fbf-5fb896b3c99e'...
    node1: ++ '[' -d /run/systemd/system ']'
    node1: ++ hostnamectl set-hostname ci-702e7442-d7b0-4726-9fbf-5fb896b3c99e
    node1: ++ systemctl restart networking.service
```

If I just started VM without provision (`vagrant up --no-provision`), I get following informations:
```
vagrant@stretch:~$ systemctl status systemd-networkd.service 
● systemd-networkd.service - Network Service
   Loaded: loaded (/lib/systemd/system/systemd-networkd.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:systemd-networkd.service(8)

vagrant@stretch:~$ systemctl restart networking
Failed to restart networking.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status networking.service' for details. 

```
Two questions:
1. What is the best way to fix this issue ?
2. I notice that the code to provision node and master are different, any reason for this ?

**Comment by nqb** [comment]
Same issue with `bento/debian-9.5` box

**Comment by drybjed** [comment]
I'm currently trying to debug this with `vagrant-lxc`, but it looks like the code that sets the hostname inside of the created VMs/containers is not functioning as expected when run by hand. I want to get some `debops.lxc` changes first, then I'll look into it a bit more.

But first, some explanation about what I'm going for with this setup. The DebOps `Vagrantfile` is meant to be used both by hand, and by the GitLab CI to setup test machines. The configuration is designed to support multi-host operation by default, since DebOps is designed to work with multiple hosts at once. However, this requires some initial setup in the test environment, namely a proper subnet with a bridge, and DNS/DHCP services that can provide IP addresses and domain resolution.

I know that Vagrant itself can do this, but I wanted the created hosts to have a fully working DNS and 
 configure everything so that they could talk to each other via hostnames instead of IP addresses. All the tools needed to make the needed environment are present in DebOps (`debops.ifupdown`, `debops.dnsmasq`), therefore the initial creation of a test environment shouldn't be that difficult. You can still use just one test host, and the project should be able to handle that situation. This is currently the case in the GitLab CI tests. In the future I would like to test multi-node configurations as well, after all of the problems are ironed out.

As for the different configuration for the `master` and `node*` hosts: the `master` host is meant to be used as an Ansible Controller, which would then control and configure the known "nodeX" hosts. That's why the "node*" host configuration in the Vagrantfile is sparse - they are meant to be configured by Ansible on the `master` host, not the Vagrant Ansible provisioner. This is done to mimic the normal, production operation of DebOps.

**Comment by nqb** [comment]
Hello,

Thanks for this complete clarification.

Do you plan to use the Ansible provisioner shipped with Vagrant to call son debops roles ?

Tip for DNS: http://xip.io

**Comment by drybjed** [comment]
It's a tricky situation. I intended Vagrant in a standalone/manual mode to provide you quick and easy setup with an Ansible Controller which you can use to apply DebOps anywhere, including on "itself", either for testing purposes, or for normal usage where you pull your inventory and project files from `git` repository and just go with them. This usage seems to be more suited from inside of the `master` VM, rather than from the ouside with Vagrant Ansible provisioner, especially that this can serve as a demo of how the `debops` command and the project directory works, without messing stuff up on the host system. So no, I don't plan to use Vagrant Ansible provisioner in this case.

`xip.io` is a nice solution when you have to use subdomains of a host, but within DebOps, hostnames themselves are used as well, for example to access the remote databases, sned logs around, etc. And with `xip.io` you would have to use the IP addresses, just with `xip.io` appended to them, instead of normal hostnames. Also, I'm trying to make DebOps environments self-sufficient and not rely on external services within the project itself - using GitHub for hosting the repo and ReadTheDocs to host the documentation doesn't count in this case because these things are not tied to the environment DebOps is managing. Therefore, reliance on locally set up subnet and `dnsmasq` instead of an external service that can vanish unexpectedly and you cannot control it yourself.

This all set up with Vagrant, GitLab CI, the `jane` script, is meant to allow you to set up your own DebOps testing environment, too. The "official" [DebOps test pipeline](https://gitlab.com/debops/debops/pipelines) is run by GitLab.com CI server and runners hosted on my infrastructure, but you should be able to easily spin up your own instance of this pipeline.

**Comment by drybjed** [comment]
This issue should now be fixed via https://github.com/debops/debops/pull/638. Would you like to test the new Vagrant setup and confirm?

**Comment by nqb** [comment]
Yes for sure but with some delay..

**Comment by nqb** [comment]
Closing this issue as a duplicate of #629.

**Comment by nqb** [comment]
See #1027
