### ISSUE TITLE
[debops.librenms] librenms role defaults to install snmp-mibs-downloader which is only available in non-default non-free debinan 9 repo

### ISSUE THREAD

**Issue by flynnsarcadenix** [debops/debops#592]
Hi Guys and Girls,
when provisioning a host with the service/librenms playbook, the used debops.librenms role defaults to installing the package snmp-mibs-downloader which is only available in the non-free repos of debian 9. These are by default not added to a debian host via the role debops.apt. This results in an error for the playbook service/librenms. Workaround for me was to add the non-free repos via ```apt__nonfree: True``` in debops.apt.
The responsable code is line 18 in roles/debops.librenms/defaults/main.yml:
```
librenms__base_packages:
  - [ 'snmp', 'imagemagick', 'fping', 'whois', 'mtr-tiny',
      'rrdtool', 'nmap', 'python-mysqldb' ]
  - '{{ "snmp-mibs-downloader"
        if (ansible_local|d() and ansible_local.apt|d() and
            (ansible_local.apt.nonfree|d())|bool)
        else [] }}'
  - '{{ "composer" if not librenms__composer_phar|bool else [] }}'
```
Debops version: 0.8.0 (looking at the commits from master for the role i wasnt able to find a related commit)

Regards,
Flynn

**Comment by drybjed** [comment]
I checked the installation of LibreNMS in a fresh container without APT `non-free` repositories enabled, and the role completes successfully. The above code should ensure that the `snmp-mibs-downloader` package is not installed if `non-free` repositories are not enabled. This issue was fixed in the https://github.com/debops/debops/commit/c3dab02002843eff6e3c3a559d6eef06440f8322 commit which is included in `v0.8.0` release.

I think that I'm confused... Do you use DebOps monorepo, or separate DebOps roles? With separate roles that probably will break in the case you describe, but the monorepo code should work fine. I'll add a note to the `debops.librenms` documentation that the `non-free` APT repository might be needed for MIBs to work as expected in LibreNMS, but otherwise I don't see a good path to enable them automatically - this decision should be deferred to the system administrator.

**Comment by flynnsarcadenix** [comment]
hi,

i use the monorepo. I agree that repo selection should be up to the sysadmin. I'm reinstalling the host and gonna try to reproduce the issue. Thank you for the quick response.

Regards,
Flynn

**Comment by flynnsarcadenix** [comment]
Ok i cant reproduce it. Lets just put a note regarding non-free in the roles documentation.

thanks
