### ISSUE TITLE
ansible-galaxy install debops.XXX always install debops.apt

### ISSUE THREAD

**Issue by tomyam1** [debops/debops#637]
I'm trying to install some debops ansible role as standalone roles.

The problem is - for **every** debops role I try to install, .e.g `debops.logrotate`, it's the `debops.apt` role that gets installed. Tried it with v0.8.0 and v0.7.2.

Anyone has a clue why this happens?

For example:

```
> ansible-galaxy install debops.logrotate --force --verbose
Using /etc/ansible/ansible.cfg as config file
- changing role debops.logrotate from v0.7.2 to unspecified
- downloading role 'logrotate', owned by debops
- downloading role from https://github.com/debops/debops/archive/v0.8.0.tar.gz
- extracting debops.logrotate to /home/jenkins/.ansible/roles/debops.logrotate
- debops.logrotate (v0.8.0) was installed successfully
```

```
> cat /home/jenkins/.ansible/roles/debops.logrotate/meta/main.yml
---

dependencies: []

galaxy_info:

  role_name: 'apt'
  company: 'DebOps'

```

```
> ansible --version
ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
> ansible-galaxy --version
ansible-galaxy 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
```

**Comment by drybjed** [comment]
The `ansible-galaxy` script is an old Galaxy client that will be at some point replaced by the `mazer` client. You should use `mazer` to download the roles from Galaxy, it supports mult-role repositories of which DebOps is an example.

Even though Ansible Galaxy web interface shows the roles separately, they are distributed in a single `git` repository, and it seems that the Galaxy team does not have plans to support installing specific Ansible roles from multi-role repositories. But that's fine, you can just install the entire repository like this:
```
mazer install debops.debops
```
And then, if you want to use specific roles you have to add their directory to the `roles_path` in the `ansible.cfg` configuration file. The `ansible-galaxy` tool does not understand the format of the multi-role repositories and that's why your install results in weird stuff like `debops.apt` role with the rest of the repository inside of it.

You can read [DebOps installation instructions](https://docs.debops.org/en/master/user-guide/install.html) for more details about using the roles via Ansible Galaxy, or other installation methods.

**Comment by tomyam1** [comment]
I see. Thanks a lot!
