### ISSUE TITLE
[debops.phpipam] What needs to be done for the phpipam role

### ISSUE THREAD

**Issue by alinalexandru** [debops/debops#661]
I want to use phpipam in our infrastructure, but it seems that this role is not completed.
Maybe it should be done as the dokuwiki role.

Identified missing integrations:
- [x] incomplete playbook
- [x] Nginx dependent configs
- [x] php dependent configs
- [x] Ferm dependent configs
- [x] Incomplete documentation
- [x] Rename phpipam_* into phpipam__*
- [x] Move from debops/phpipam upstream into the maintainer git

Is there anything else missing from the list above?

**Comment by drybjed** [comment]
Indeed, `debops.phpipam` role hasn't been touched for a while. I would start first by moving the dependencies in the `meta/main.yml` file of the role to the playbook (leave `debops.secret` since it's a hard dependency).

You could also switch from the `debops/phpipam` fork to the upstream. The fork was done when phpIPAM was not available on GitHub, or even as a `git` repository somewhere. Since [the project is on GitHub now](https://github.com/phpipam/phpipam), we can switch to the upstream version.

The next step after that would be variable namespacing, from `phpipam_*` to `phpipam__*` variables. After that I would look into cleaning up some old practices in the role, converting the configuration file to use custom DebOps merge filters, etc.

Thanks for picking that up. Let me know if you find any issues. :-)

**Comment by alinalexandru** [comment]
@drybjed Do you want to move from `meta/main.yml` to `service/phpipam.yml`, or vice versa?

**Comment by drybjed** [comment]
Move the role dependencies from `ansible/roles/debops.phpipam/main.yml` to `ansible/playbooks/service/phpipam.yml`. Just leave the `debops.secret` dependency in the `meta/main.yml` file of the role.

**Comment by alinalexandru** [comment]
Should I keep the BC?
For example, ``phpipam__git_dest: {{ phpipam_git_dest }}`` ?

**Comment by drybjed** [comment]
Backwards Compatibility? No, since it will be a total role rewrite I don't think that you need. We can add a note to upgrade notes that all `phpipam_*` variables have been renamed and users will have to update their inventory variables.

**Comment by alinalexandru** [comment]
@drybjed Should I have to move the variables from `vars/main.yml` to `defaults/main.yml`?
In my opinion I have to do that.

**Comment by drybjed** [comment]
Yes, definitely. Then they can be overridden via inventory if needed.

**Comment by alinalexandru** [comment]
@drybjed Should I include https://github.com/debops/phpipam-scripts into the role itself?

**Comment by drybjed** [comment]
I'd say, no. `phpipam-scripts` is a horrible, old hack that scrapes the phpIPAM database directly. A better solution that uses the API instead should be written, that way you would have to have access to the database itself.

**Comment by alinalexandru** [comment]
I don't think I have time now for that. First I wanna finish this ticket, and in the future to add also this feature.
