### ISSUE TITLE
Nextcloud tutorial

### ISSUE THREAD

**Issue by 19hundreds** [debops/debops#675]
I just published a sort of tutorial which, out of the box, spins off a virtual machine with Nextcloud 15 configured.

https://github.com/19hundreds/nextcloud_with_debops

I hope it helps

**Comment by drybjed** [comment]
@19hundreds Thanks, looks impressive! Although I have two nitpicks:

It would be excellent if you could keep the name and spelling of "DebOps" when you speak about the project as a whole; "debops" should be reserved for the included scripts. This is because there are different spellings of "debops" out there, and it should help enforce the distinction between DebOps and "DevOps".

> Let it run. It takes a long time, like an hour.

I think that adding some reasons why it might take this long might be useful to other users. DebOps installs multiple APT packages at different times, some software is installed from source, that can take a long time. However, the underlying infrastructure and hardware can also be a factor - on a slow hard drives and inside of a VM the install of some bigger applications like Nextcloud and GitLab can tak 1-2 hours, but when run directly on hardware, or with a fast storage array as a backing store, the same playbook can take 10-20 minutes, depending on network speed and other resources.

Otherwise, good work. And thanks for sharing!

**Comment by 19hundreds** [comment]
agreed, all the way. And fixed, already. :-)

Thank you for the fantastic job!
