### ISSUE TITLE
apt.proxy seems not to work as intended (for me?)

### ISSUE THREAD

**Issue by stefangweichinger** [debops/debops#696]
Tried to apply the proxy-url to my hosts via group_vars/all/apt_proxy.yml:

```
apt_proxy__http_url: 'http://192.168.97.160:3142/'
```

The copy task failed: 

```
task path: /home/sgw/.local/share/debops/debops/ansible/roles/debops.apt_proxy/tasks/main.yml:13
skipping: [some.host] => {"changed": false, "skip_reason": "Conditional result was False"}
```

Only after removing the when-clause (line 13) and defining:

```
apt_proxy__deploy_state: 'present'
apt_proxy__proxy_auto_detect: '/usr/local/lib/get-reachable-apt-proxy'
```

the configfile was copied.

The proxy was online all the time, I tested via telnet, and also after copying the file the proxy was used correctly immediately.

**Comment by drybjed** [comment]
The `skip_reason` value suggests that the variables checked in the `when:` condition could have wrong values. Can you add before that task:
```yaml
- debug: var=apt_proxy__deploy_state
- debug: var=apt_proxy__temporally_avoid_unreachable
```
and show the result?

**Comment by stefangweichinger** [comment]
It seems to work now!? Was it your commit b43d5d0 ?

**Comment by drybjed** [comment]
@stefangweichinger Actually, perhaps? That commit removed the `validate` parameter from the task, but I'm not really sure how would that affect your environment. Perhaps your firewall blocks connections to `https://example.org/` and that's why the task was not valid? You could check by adding that parameter and seeing if this breaks the role again.
