### ISSUE TITLE
The pki_enabled=False setting should overlap in the role

### ISSUE THREAD

**Issue by thiagotalma** [debops/debops#756]
Even when we define `pki_enabled = False` the role still performs many unnecessary tasks, it ends up generating some errors and forcing us to clear other default settings.

In setting up a development environment this situation is very annoying.

**Comment by drybjed** [comment]
Hi, thanks for the bug report. The `debops.pki` role is unique in that it works both on the remote hosts, and the Ansible Controller. the `pki_enable` toggle turns off the portion of the role that works on the remote hosts, but that's more tricky to design for the Ansible Controller, since you could disable PKI only partially, for specific hosts - in that case Ansible Controller still needs to be able to sign incoming certificate requests.

You could disable CA management on the Ansible Controller by ensuring that the `pki_authorities` and `pki_dependent_authorities` lists are empty. That should do the trick, if it doesn't, let me know.

However, I would be more interested in knowing why you want to disable `debops.pki` in the first place? I would think that you would want to use it in the development environment as well, to ensure that it is as similar as your production environment, correct? Any reasons behind this decision?

Also, if you show the errors you are getting, perhaps they could be fixed in the role or correct solutions could be found to avoid them.

**Comment by thiagotalma** [comment]
Thank you for the explanation. You're right.

**Comment by drybjed** [comment]
@thiagotalma Umm, OK, but did you manage to resolve your issue? Any hints to what could cause the problem so that we could fix it in the role?

**Comment by thiagotalma** [comment]
@drybjed Unfortunately I do not remember what the error was, but something related to the certificate generation. In case it happens again I send a PR.

But the best solution is to clear the lists in the development environment.
If it were to adjust the role, I would guarantee that any task would respect the option of disabling the pki, nothing would be executed.

Thank you very much for your attention!

My setup looks like this:

```YAML
pki_enabled: False

pki_acme: False

pki_authorities: []

pki_dependent_authorities: []

pki_default_realms: []
```
