### ISSUE TITLE
[debops.apache] 'resources__src' is undefined

### ISSUE THREAD

**Issue by mikenowak** [debops/debops#760]
Hi @drybjed,

I am having the following while running apache role.

```
TASK [debops.apache : Create conf-available snippets] *********************************************************************************************************************
failed: [apache.example.co.jp] (item={'value': True, 'key': u'local-debops_apache'}) => {"changed": false, "item": {"key": "local-debops_apache", "value": true}, "msg": "AnsibleUndefinedVariable: 'resources__src' is undefined"}
```

and the below is the source of this from my inventory.

```
ansible/inventory/group_vars/all/resources.yml:  - src: '{{ resources__src + "etc/ssh/banner.txt" }}'
```

**Comment by drybjed** [comment]
This might be caused by two things:

- outdated Jinja library, do you use Jinja 2.10?
- variable from the `debops.resources` role defined in a file in the inventory which also contains `debops.apache` variables. In essence, if you stick to putting variables per role in separate files in the inventory, the ones that are not "resolvable" in the current playbook should be silently ignored by Ansible. If you mix variables from different roles that are not applied in the same playbook (say, `debops.apache` and `debops.resources`) in the same file in the inventory, some variables will not be able to be resolved and Ansible will create random errors like the above where one role seemingly references variables from other random role.

Also, what Ansible version are you using?

**Comment by mikenowak** [comment]
Yes, Jinja2 (2.10) is in use.

I use separate files, here is an idea looking down ansible/inventory/group_vars - included only a few examples 

```
── all
│   ├── apt.yml
│   ├── apt_install.yml
│   ├── resources.yml
├── webapp
│   ├── apache.yml
│   ├── apt_install.yml
```

Then, `all/resources.yml` contains only `resources__files`, and nothing apache related.

Also, `webapp/apache.yml` does not appear to contain anything that wouldn't be apache related.

Ansible version: ansible 2.7.8 - let me know if I need to upgrade/downgrade

**Comment by drybjed** [comment]
Well, the above seems to be fine... What's the command you are using to apply the playbook?

Try this. Add the `debug` tag to the task that causes an error and run the playbook with:
```
debops service/apache -l host -t debug --check
```
See if the error shows up, if it's there you can then start debugging. Clear out your inventory leaving the `hosts` file and run the above command again. If there's an error, the bug is in the playbook/role, if not, it's in the inventory.

If it's the latter, add some inventory files and run the command periodically to see when the bug comes back. Then you will know where the issue might be.

**Comment by mikenowak** [comment]
@drybjed hi,

just an update - I've ignored this for a while, as it wasn't a priority. Today I did a `debops-update`, and now all these undefined variables are gone. 

However, there is a new issue, which appears to have something to do with the template.

```
failed: [host.example.co.jp] (item={'value': True, 'key': u'local-debops_apache'}) => {"changed": false, "item": {"key": "local-debops_apache", "value": true}, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ lookup(\"template\", \"lookup/ferm__fix_dependent_rules.j2\", convert_data=False) | from_json }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'template'. Error was a <class 'ansible.errors.AnsibleError'>, original message: the template file lookup/ferm__fix_dependent_rules.j2 could not be found for the lookup"}
```

As far as I understand this, the error doesn't appear to make sense since the template exists - `~/.local/share/debops/debops/ansible/roles/debops.ferm/templates/lookup/ferm__fix_dependent_rules.j2`.

**Comment by mikenowak** [comment]
closing this off, I no longer have the need to run apache for this application. Also nginx is behaving as expected.
