### ISSUE TITLE
[debops.pki] Add troubleshoting section for ACME support 

### ISSUE THREAD

**Issue by htgoebel** [debops/debops#774]
I (again) just had a hard time figuring out whether ACME certificates have been generated, why not and how to re-run the generation. Please add a short troubleshoting section to acme-integration, stating that /etc/pki/realms/$realm/acme/error.log need to be checked and deleted.

**Comment by imrejonk** [comment]
One of our servers (support2.ciphermail.com) had an interesting renewal failure recently, which was related to this issue. What happened was this:

1. The renewal attempt started on 2021-04-11 00:00:01.000 +02:00. `/etc/cron.d/pki-realm-scheduler` specifies `@weekly` as the execution time, which on this system translates to every Sunday at one minute past midnight.
2. The Let's Encrypt validation servers appear to have been busy at that time, because the secondary validation failed with a DNS error. If I'm not mistaken, this means that the initial validation succeeded, but because Let's Encrypt uses [multi-perspective validation](https://github.com/letsencrypt/boulder/blob/master/docs/multi-va.md), the whole validation process can still fail if an error occurs at one of the other vantage points.
3. The following was logged to /etc/pki/realms/nginx/acme/error.log:
```
Parsing account key...
Parsing CSR...
Found domains: support.ciphermail.com, support2.ciphermail.com
Getting directory...
Directory found!
Registering account...
Already registered!
Updated contact details:
mailto:tech@ciphermail.com
Creating new order...
Order created!
Verifying support.ciphermail.com...
Traceback (most recent call last):
  File "/usr/local/lib/pki/acme-tiny", line 198, in <module>
    main(sys.argv[1:])
  File "/usr/local/lib/pki/acme-tiny", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/usr/local/lib/pki/acme-tiny", line 149, in get_crt
    raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
ValueError: Challenge did not pass for support.ciphermail.com: {'identifier': {'type': 'dns', 'value': 'support.ciphermail.com'}, 'status': 'invalid', 'expires': '2021-04-17T22:00:42Z', 'challenges': [{'type': 'http-01', 'status': 'invalid', 'error': {'type': 'urn:ietf:params:acme:error:dns', 'detail': "During secondary validation: DNS problem: SERVFAIL looking up A for support.ciphermail.com - the domain's nameservers may be malfunctioning", 'status': 400}, 'url': 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/12238541917/_VJG-A', 'token': 'cpFsE9a1BJdCZSSTgpwuemauC-wS9v4_CvW6645XQWU', 'validationRecord': [{'url': 'http://support.ciphermail.com/.well-known/acme-challenge/cpFsE9a1BJdCZSSTgpwuemauC-wS9v4_CvW6645XQWU', 'hostname': 'support.ciphermail.com', 'port': '80', 'addressesResolved': ['87.233.242.85', '2001:9a8:135::1:e7cc'], 'addressUsed': '2001:9a8:135::1:e7cc'}], 'validated': '2021-04-10T22:00:44Z'}]}
```
4. Let's Encrypt sent a certificate expiration notice on Thursday, April 15 at 10:35 (20 days before expiration).
5. Our monitoring system sent a warning on Thursday, April 15 at 10:49.
6. The next attempt should have been on April 18th, but this renewal attempt was skipped because the error.log file existed.
7. We intervened on April 19th by removing the error.log file and manually running the cron job. The renewal succeeded this time.

Here's what we did to prevent this from happening again:

1. A simple change to `request_acme_tiny_certificate()` in the pki-realm script:
```
--- debops/ansible/roles/pki/files/usr/local/lib/pki/pki-realm	2021-04-19 13:12:01.794009062 +0200
+++ ansible/roles/pki/files/usr/local/lib/pki/pki-realm	2021-04-19 13:11:46.753952139 +0200
@@ -1172,6 +1172,11 @@
                 rm -f acme/cert.pem.tmp
             fi
 
+            # Rotate acme/error.log to ensure another renewal attempt
+            if [ -e acme/error.log ] ; then
+                mv acme/error.log "acme/error-$(date +%s).log"
+            fi
+
         fi
 
     fi
```
2. Disabled `pki_scheduler` and configured a custom cron job that lives in /etc/cron.daily/pki-realm-scheduler. This job is executed according to the pseudo-random times in /etc/crontab. The daily execution also ensures a faster renewal attempt.

What do you think of this solution? I'm sure it's not perfect, but it works for now.

**Comment by drybjed** [comment]
The script skipping ACME renewal when the `acme/error.log` file is present is mostly to avoid hitting rate limits, but that seems only relevant when you set everything up. When the infrastructure is set up, having that restriction is most likely unnecessary and creates this problem in the first place.

I think that you are onto something here. How about tweaking your solution like this: move the rotation before the ACME request happens, check if the file exists and if it's older than say, 1 day. Then during initialization phase the file will prevent hitting rate limits and will have to be removed manually, and during normal operation the `pki-realm` script running on a weekly basis should rotate the log file and make a new ACME request. Presence of many such log files could indicate some other issue which can then be investigated by the admin.

**Comment by imrejonk** [comment]
**Edit:** forgot to add a test for acme/error.log existence

Thanks for your thoughts on this, @drybjed. It seems sensible to use the error.log file as a kind of lock file to prevent hitting rate limits. I have now modified my pki-realm script like this:

```
--- debops/ansible/roles/pki/files/usr/local/lib/pki/pki-realm	2021-04-19 13:12:01.794009062 +0200
+++ ansible/roles/pki/files/usr/local/lib/pki/pki-realm	2021-04-28 17:20:37.979544030 +0200
@@ -1078,6 +1078,14 @@
 
 request_acme_tiny_certificate () {
 
+    # Rotate acme/error.log if it was modified more than two days ago. This
+    # allows another renewal attempt, but still prevents hitting rate limits.
+    # Let's Encrypt limits duplicate certificate requests to five per week
+    # (https://letsencrypt.org/docs/rate-limits/).
+    if [[ -e acme/error.log ]] && [[ `find acme/error.log -mtime +1` ]]; then
+        mv acme/error.log "acme/error-$(date +%s).log"
+    fi
+
     if [ "${config['pki_acme']}" = "true" ] && [ -x "${config['acme_client_script']}" ] && [ -d "${config['acme_challenge_dir']}" ] && [ ! -e acme/error.log ] && [ -r acme/request.pem ] ; then
 
         if ! ( check_expiration_time acme/cert.pem "${config['acme_expiration_seconds']}" && check_openssl_key_crt_match private/key.pem acme/cert.pem ) ; then
```

I believe that the Certbot client performs certificate renewal checks twice per day. The idea is that Let's Encrypt may also revoke a certificate, and being able to quickly renew after a revocation allows a website to stay online thanks to OCSP stapling. OCSP responses are often valid for 48 hours, so website visitors shouldn't see any scary security warnings.

**Comment by drybjed** [comment]
@imrejonk So the edit means that you had a chance to see the new changes in action? If they work as expected you can make a PR. :-)

**Comment by imrejonk** [comment]
Yeah I'm testing it now, a PR will follow soon
