### ISSUE TITLE
[debops.ansible_plugins] Rework and unit test filter_plugins/debops_filter_plugins.py

### ISSUE THREAD

**Issue by ypid** [debops/debops#776]
I started using `parse_kv_items` and `parse_kv_config` heavier and need to extend them as I want them to support more nesting levels. The functions share some code and are not unit tested. This makes it difficult to extend them. I am in the process of reworking them.

Maybe give me a few days until I have extended, unit tested and tested them with regular DebOps usage :)

**Comment by drybjed** [comment]
Sure, glad you like them. :) I'm thinking about a support for recursive nesting of configuration sections, I think that `nginx` is one of the services that supports this... Also `dhcpd`, `named` I think? As for implementing, I suppose that a specific key used in a dictionary could have a list of dictionaries that's expanded recursively. Merging multiple entries recursively would be a bonus at this point.

I'll try to make a new release in a few days, so that there's a good working version of the code we can build upon.
