### ISSUE TITLE
bootstrap__packages list is ignored

### ISSUE THREAD

**Issue by chymian** [debops/debops#813]
Hi, 
while I tackled the yadm-bootstrap issue, which you already fixed now, I realized, that the `bootstrap__packages` list is ignored.
I tried to install yadm via the list w/o success and found out, that other packages in that list are also not installed. 
a few of them get installed from other roles but the rest is missing, i.e. bash-completion, yadm, ...
```
bootstrap__packages:
    - git
    - make
    - bash-completion
    - most
    - ssh
    - apt-transport-https
    - ca-certificates
    - sudo
    - curl
    - wget
    - gnupg2
    - software-properties-common
    - yadm
```

Question: should it be possible to use something like `yadm/stretch-backports` in that list?

**Comment by drybjed** [comment]
The `debops.bootstrap` role has been removed from DebOps; most of its functionality is now split between various new roles. Do you plan to use the `common.yml` playbook as well? In that case I would probably add most of these packages to the `apt_install__packages` list instead.

Some of these packages should be handled by separate DebOps roles. There's `debops.sudo` role which supports installing `sudo` or `sudo-ldap` depending on LDAP support on the host. The `yadm` package has its own role, which coincidentally will install the `stretch-backports` version by setting up an APT pin. The `ca-certificates` package will be handled by the `debops.pki` role, `apt-transport-https` is included in the `debops.apt` role, and so on.

Using `yadm/stretch-backports` in the package list like that will not work, since the release is a separate `apt` module parameter. I would go with APT pinning instead, handled by the `debops.apt_preferences` role.

**Comment by chymian** [comment]
with the boostrap removed, how should pks like python get installed, to be able to run normal debops playbooks?
even preseeded vms by `debops.preseed ` do not have it. basic VMs from other providers may also be just debian-minimal?
what do I miss?

**Comment by drybjed** [comment]
The bootstrap "playbook" still exists, you can [view it here](https://github.com/debops/debops/blob/master/ansible/playbooks/bootstrap.yml). You still set up new hosts as normal, using the command:
```
debops bootstrap -l <host> -u root
```
Just instead of one `debops.bootstrap` role, there are multiple roles that perform specific ations at bootstrap time. The `debops.python` role has a special "sub-role" that is executed by the bootstrap playbook and installs the needed Python packages. There's even a new [`bootstrap-ldap.yml` playbook](https://github.com/debops/debops/blob/master/ansible/playbooks/bootstrap-ldap.yml) which can be used to set up a host with LDAP directory access from the get-go.

Of course after bootstrapping you should apply the `common.yml` playbook as well, which sets up some additional packages and services.

**Comment by chymian** [comment]
thanks for outlining.
