### ISSUE TITLE
[debops.docker_server] path to docker daemon for all distributions managed by DebOps

### ISSUE THREAD

**Issue by nqb** [debops/debops#911]
Next part of #820 and #909 

See @drybjed's comment:

> Now that I think about it, this will break on Bullseye and beyond. Perhaps you could invert the condition, use the old path on all the old Debian/Ubuntu releases, and otherwise use the new one? For Ubuntu, you can just stick to LTS releases (trusty, xenial, bionic).

**Comment by nqb** [comment]
@drybjed, is binary in same location when `docker` is installed from upstream and distribution packages ?

**Comment by drybjed** [comment]
I'm not sure, but this should be easy to check. The [`docker.io` package in Debian](https://sources.debian.org/src/docker.io/18.09.1+dfsg1-7.1/engine/contrib/init/systemd/docker.service/#L14) has it as `/usr/sbin/dockerd`.

Perhaps this should be based on the Docker version instead, assuming that the `docker-ce` package from upstream and `docker.io` package from Debian use the same numbering scheme. Version is already exposed as `docker_server__version` and could be used with the `version` Ansible filter to pick the correct path. I'm not sure when the change happened though.

**Comment by nqb** [comment]
Unfortunately, upstream packages installed `dockerd` binary in `/usr/bin/` (tested on Buster):

```console
vagrant@debops-d7dfea-node2:~$ ls -rtl /usr/bin/dockerd
lrwxrwxrwx 1 root root 25 Jul 19 15:25 /usr/bin/dockerd -> /etc/alternatives/dockerd
vagrant@debops-d7dfea-node2:~$ ls -rtl /etc/alternatives/dockerd 
lrwxrwxrwx 1 root root 19 Jul 19 15:25 /etc/alternatives/dockerd -> /usr/bin/dockerd-ce
```

**Comment by drybjed** [comment]
Hmmm, tempting, but I don't think that `systemd` would accept `/etc/alternatives/dockerd` as the executable... Did you check the version from upstream?

But I know how we can utilize that symlink - the `debops.docker_server` fact script could check the link target, or some other common locations for an existing binary, and return that as `ansible_local.docker_server.dockerd_binary` which then can be either used directly in the unit template, or exposed via a default variable so that users can change it, if it's useful.

Edit: I'll wait with merging https://github.com/debops/debops/pull/912 until we solve this.

**Comment by nqb** [comment]
> Did you check the version from upstream?

Same version scheme from facts between upstream and distribution packages.

> But I know how we can utilize that symlink - the `debops.docker_server` fact script could check the link target, or some other common locations for an existing binary, and return that as `ansible_local.docker_server.dockerd_binary` which then can be either used directly in the unit template, or exposed via a default variable so that users can change it, if it's useful.

I understand.

**Comment by nqb** [comment]
@drybjed, did you plan to work on it ? 

My current knowledge of Python and time are too limited to fix it quickly.

**Comment by drybjed** [comment]
@nqb Sure, I will look into it soon.
