### ISSUE TITLE
debops.docker not compatible with upstream version of docker for debian buster

### ISSUE THREAD

**Issue by lhernanz** [debops/debops#977]
When using debian buster, the` execstart-override.conf.j2` template sets the path of the dockerd binary to point to `/usr/sbin` instead of `/usr/bin`. This is fine for the docker package included in the distribution, but if you set the role to download the upstream package, that still uses the `/usr/bin` path and, therefore, the daemon does not start.
As of today, the distro version does not work on raspbian, so this is inconvenient.
Debops 1.0.7 on raspbian buster.

**Comment by drybjed** [comment]
Thanks for the bug report. This has [already been fixed in the `master` branch](https://github.com/debops/debops/commit/674412fad89a44145d66e394ad70ae4baa7944d9), unfortunately I cannot backport this to `stable-1.0` because of the role name change, from `debops.docker` to `debops.docker_server`.

I would suggest that you try the `master` DebOps release instead. According to the [current release schedule](https://docs.debops.org/en/master/news/releases.html#current-release-schedule) next `stable-1.1` release will be done in at most two weeks, so you could wait until then if you want.

**Comment by lhernanz** [comment]
Amazing! Thanks, I will wait until the 1.1. release. Keep the good work.

**Comment by drybjed** [comment]
This issue should be solved with the DebOps v1.1.0 release, closing.
